image: node:8.12.0

pages:
  cache:
    paths:
      - node_modules/

  stage: deploy
  script:
    - npm install -g @angular/cli@7.0.6
    - npm install
    - ng build
    - mkdir -p public
    - mv dist/PodTrackerAngularClient/* public/
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
